server:
  port: 3000
spring:
  datasource:
#    url: jdbc:mysql://l21.196.161.100:3306/xiaomi?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/xiaomi?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 121.196.161.100
    password: JQF04026
  rabbitmq:
    host: 121.196.161.100
    port: 5672
    username: admin
    password: admin
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


logging:
  config: logback.xml
  level:
    com.jang.Mishop.mapper: trace